# Generated by Django 3.2.9 on 2021-11-19 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nid',
            field=models.BigIntegerField(default=None),
        ),
    ]
